### PR TITLE
dev: Pushing up MVP for frontend; minor changes to backend as well

### PR DESCRIPTION
**Pull request by jshilts657**
This is the MVP for the frontend.

It is also already containerized but be warned I have not tested the container yet.

In order to run this atm you need to cd into the frontend repo and from the command line enter `npm start`
This is of course after you have already started the flask backend.

### CODE REVIEW

**Review by Rekik27 — APPROVED** [review]
It is looks good

**Review by jamzheng109 — APPROVED** [review]
looks good

**Review by BlueGreenDragon — APPROVED** [review]
Approved, but GitHub is saying that there are conflicts.

**Comment by jshilts657** [comment]
> Approved, but GitHub is saying that there are conflicts.

Thank you for pointing that out I did not see that conflicts have been resolved

**Pull request merged**
