### PR TITLE
Feature/refactor docker pushing

### PR DESCRIPTION
**Pull request by rzheng2019**
Restructured workflow structure and removed Docker image pulling jobs

### CODE REVIEW

**Review by jamzheng109 — APPROVED** [review]
looks good

**Review by jshilts657 — CHANGES_REQUESTED** [review]
Everything looks good.
Since I merged I think all you need to do is merge dev and that's it.

**Review by jshilts657 — APPROVED** [review]
looks good

**Review by BlueGreenDragon — APPROVED** [review]
Looks good.

**Pull request merged**
