### PR TITLE
Feature/movies db

### PR DESCRIPTION
**Pull request by jshilts657**
This is a Collab space to refactor some of the db work to better integrate with the pipeline, deployment, and overall software architecture.

### CODE REVIEW

**Comment by jshilts657** [comment]
So I think the first thing we should do here since you also wrote the test script is update the directory structure so that the test code you wrote matches the arch of the other files.

in database dir create:
    src folder
    test folder
    
// If we had more data I'd say make a data folder but the csv might as well just go into src folder to limit refactoring on your end.    

I would then move to src:
create_movies_db.py
create_movies_db_tables.py
the data
load_movies_db_data.py
start_movies.py

then move to test:
db_test.py
db_test_data.py

Re run you code and update all required pathways.

**Comment by jshilts657** [comment]
@BlueGreenDragon 
I just pushed some changes up that do the following
Convert test framework from unittest to pytest: So we can leverage same logic from how the backend is being run in pipeline.
Removed test class and just used function because it was causing issues with PyTest.
rerouted all pathways in both test and production to point to only one database, the one in src.
Ran new unit test locally and it passed.

I think this is ready to bring out of draft and ready for a formal PR.


There is still some clean up to be done.
Make sure all other tests run
Remove old unused files
Update Readme with run direction for both data docker container and tests.

**Comment by jshilts657** [comment]
@TrevorMichelsonBU 
Just want to make sure that this is noted.
The majority of this work was done by @BlueGreenDragon  I am just merging because we had alot of dev enviroment configuration issues and we need the database to unblock other portions of our work so I just created the PR and integrated it into the pipeline.

**Review by jamzheng109 — APPROVED** [review]
looks good

**Review by BlueGreenDragon — APPROVED** [review]
Looks good.

**Review by rzheng2019 — APPROVED** [review]

**Pull request merged**
