### PR TITLE
Database Information

### PR DESCRIPTION
**Pull request by acflinch**
Added Database Requirements and Database UML Diagram to docs

### CODE REVIEW

**Review by BlueGreenDragon — APPROVED** [review]
Looks good.

**Review by jshilts657 — CHANGES_REQUESTED** [review]
Needs to be merged into dev not main

**Review by jshilts657 — APPROVED** [review]

**Review by BlueGreenDragon — CHANGES_REQUESTED** [review]
Sorry to reverse my review. On second look I have questions and will put them in the chat.

**Review by rzheng2019 — APPROVED** [review]

**Review by BlueGreenDragon — CHANGES_REQUESTED** [review]
Did you get a chance to update the Database Requirments.docx? When I looked at it, the Data Dictionary only needs minor updates to Rank (missing?), Budget, Box_office, and the list of Foreign Keys. We should mention that we're changing the name of Certificate to Age_Rating. Let me know if you don't have the bandwidth and I'll take care of it.

**Review by BlueGreenDragon — APPROVED** [review]

**Pull request merged**
